[project]
name = "vt2fql"
version = "1.0.0"
description = "Generate Falcon FQL queries from VirusTotal"
authors = [{ name="Omar Haggag" }]
dependencies = ["click", "vt-py", "python-dotenv"]
requires-python = ">=3.8"

[project.scripts]
vt2fql = "vt2fql.cli:main"